# Generated by Django 4.2.2 on 2023-06-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0006_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="likes",
        ),
        migrations.AddField(
            model_name="like",
            name="is_dislike",
            field=models.BooleanField(default=False),
        ),
    ]
